_BASE_: "../../Base-RCNN-FPN.yaml"

MODEL:
  WEIGHTS: "/home/sjk/ZJX/FSCE/outputs/R101_FPN_base_training_split1_all_dynamic_cos/model_reset_surgery.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101

  BACKBONE:
    FREEZE: True
    FREEZE_AT: 5

  PROPOSAL_GENERATOR:
    FREEZE: True
  RPN:
    POST_NMS_TOPK_TRAIN: 2000

  ROI_HEADS:
    NUM_CLASSES: 20
    OUTPUT_LAYER: "CosineSimOutputLayers"
    FREEZE_FEAT: True
    UNFREEZE_FC2: True
    BATCH_SIZE_PER_IMAGE: 256
    IOU_THRESHOLDS: [0.4]

INPUT:
  CROP:
    ENABLED: TRUE
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800

DATASETS:
  TRAIN: ('voc_2007_trainval_all2_10shot',)
  TEST: ('voc_2007_test_all2',)

SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.0005
  STEPS: (4500,)
  MAX_ITER: 7000
  CHECKPOINT_PERIOD: 6000
  WARMUP_ITERS: 200

TEST:
  EVAL_PERIOD: 6000

OUTPUT_DIR: "/home/sjk/ZJX/FSCE/outputs/10shot_baselinesplit1_al_attention_bs16_dynmic_cos"